martian-dao/aptos-web3.js

package-lock.json, package.json
=> fix: Fix using unadded packages

.eslintignore, package.json, src/wallet_client.test.ts, src/wallet_client.ts
Bug fix
https://martiandao.atlassian.net/jira/software/projects/WAL/boards/1?selectedIssue=WAL-156
tests added in the pipeline
Potentially risk for wallet APIs. TODO: Check compatibility with extension.
* 
* **Note**:
1. Make sure that your …
=> resolving lint errors

docs/.nojekyll, docs/README.md, docs/classes/WalletClient.md, docs/interfaces/AccountMetaData.md, docs/interfaces/TokenId.md, docs/interfaces/Wallet.md, docs/modules.md, package.json, src/wallet_client.ts
Added typedoc and typedoc plugin markdown to generate markdown docs of the documentation
https://martiandao.atlassian.net/jira/software/projects/WAL/boards/1?assignee=62571e61410206006e972e99&selectedIssue=WAL-157
=> adding comments and typedoc

src/wallet_client.ts
Bug fix
Based on this PR:
https://github.com/aptos-labs/aptos-core/pull/2189
"verify fungible tokens" tests the code for this
* 
* **Note**:
a. You have done your …
=> update register coin call

package.json, src/faucet_client.ts, src/wallet_client.test.ts, src/wallet_client.ts
Bug Fix
Issue #9 
Trimmeing extra zeroes from the begining of a address
No
* 
* **Note**:
a. You have done your changes in a separate branch. Branches MUST have …
=> Added toShortString for account metadata

src/aptos_client.ts
Bug fix
Currently getting system time for the expiration_timestamp_secs
Fetching ledger_timestamp instead of system time
tested it on wallet_client.test.ts
Yes, if something getLedgerInfo API breaks transaction will throw error
* 
* **Note**:
Please, go through these steps before you submit a …
=> Getting timestamp from aptos instead of system time

src/aptos_client.ts
update
gas_currency_code is "XUS"
Updated gas_currency_code to "APT"
Tested it on wallet_client.test.ts
Yes
* 
* **Note**:
a. You have done your changes in a …
=> Changed currency from XUS to APT

src/aptos_client.ts
- [ x] Tests for the changes have been added (for bug fixes/features)
Bug fix
Expiration timestamp is incorrectly sent as microsecs
Changed it to send secs
* 
* **Note**:
2. If not, then make …
=> changed microsecs expiration to secs

package.json, src/aptos_client.test.ts, src/wallet_client.ts
Bug fix
Edge cases are not handled in getTokenIds
Handled edge cases
npm run test
No
* 
* **Note**:
a. You have done your changes in a separate branch. Branches …
=> Removed undefined, bug fix in aptos_client.test

src/aptos_account.ts, src/wallet_client.test.ts, src/wallet_client.ts
- [ x] Tests for the changes have been added (for bug fixes/features)
Modified BIP44 to support SLIP10 because of ed25519 curve
We were using secp256k1 curve instead of ed25519 for account management.
Added support for ed25519
User's need to be advised that they will need to create new accounts after this change is …
=> changed to slip10 & disabled key rotation

package.json
Update
Version is V1.1.19
Changed it to V1.1.20
No
No
* 
* **Note**:
a. You have done your changes in a separate branch. Branches MUST have descriptive names that …
=> Changed version from V1.1.19 -> V1.1.20

src/wallet_client.ts
Bug fix / Update
registerCoin function is using function 0x1::coins
It is changed in aptos and now updated it to 0x1::managed_coin
No
No
* 
* **Note**:
a. You …
=> changed 0x1::coins to 0x1::managed_coin

src/wallet_client.ts
Bug fix
Currently unpadded publicKey is returned from importWallet and createWallet
Returning padded publicKey from importWallet and createWallet
No
* 
* **Note**:
2. If not, then make sure …
=> Changed toShortString -> toString for publicKey

src/wallet_client.ts
Change of payload for initializing coins
Current payload doesn't comply with TS SDK payload
Updated the payload
* 
* **Note**:
a. You have done your changes in a …
=> updates initializeCoin

src/transaction_builder/builder.ts
Bug fix
ledger timestamp gives microseconds
converting it to seconds and passing
No
* 
* **Note**:
a. You have done your changes in a separate branch. Branches …
=> fixed ledger timestamp

package.json
Version update
version is v1.1.22
updated to v1.2.1
No
* 
* **Note**:
a. You have done your changes in a separate branch. Branches MUST have descriptive names …
=> updated version from v1.1.22 -> v1.2.1

package.json, src/index.ts
Bug fix
wallet client is not exported
fixed the issue
No
* 
* **Note**:
a. You have done your changes in a separate branch. Branches MUST have descriptive names …
=> bug fix: exporting wallet client

package.json, src/generated/core/request.ts
Code cleanup / version update
unwanted console.log was present
removed console log and updated the version number
No
* 
* **Note**:
a. You have done your changes …
=> removed console.log and version update

src/wallet_client.test.ts, src/wallet_client.ts
Bug fix
The derivation path in getAccountFromMnemonic was incorrect
Fixed the derivation path
* 
* **Note**:
a. You have done your changes in a separate branch. …
=> fixed getAccountFromMnemonic

package.json, src/aptos_client.ts, src/coin_client.ts, src/generated/core/request.ts, src/generated/services/BlocksService.ts, src/token_client.ts, src/transaction_builder/builder.ts, src/utils/misc.ts, src/utils/test_helper.test.ts, src/wallet_client.ts
Update
Old aptos sdk was used
updated with the latest changes in aptos core sdk
npm run test
No
* 
* **Note**:
a. You have done your changes in a separate branch. …
=> updated sdk according to new aptos changes, updated sdk version

src/wallet_client.ts
Bug fix
Public package was changed from aptos SDK and we had to change the logic
Fixed the public package function
Manually tested
No
* 
* **Note**:
a. You have …
=> added publish package

src/wallet_client.ts
Update
We are currently using the coin::transfer function. If a user sends tokens to an account which does not already exist, this leads to an error and we want to support sending tokens to unregistered accounts.
Changed the function to aptos_account::transfer. This will now create the recipient account if it doesn't already exist
Manually tested
* **Does this PR introduce a breaking change?** (What changes might users need to make in their …
=> updated the transfer function

.gitignore, package.json, src/generated/core/fetch-adapter.js, src/generated/core/request.ts
Bug fix
dist folder is in .gitignore which causes npm pack to ignore distribution files
removed dist folder
* 
* **Note**:
a. You have done your changes in a …
=> removed dist folder from .gitignore, updated version

src/wallet_client.ts
Reverts martian-dao/aptos-web3.js#60
=> Revert "harsh/handle-burn-events-in-nfts"

src/wallet_client.ts
Bug fix
When a token handle is not found (for some reason), this function throws an error. We'll take care of the token handle problem (if from our side) in a later PR. 
Rest of the tokens are returning correctly now
Checked it for a user's account for whom the NFTs were not being displayed on testnet.
* **Other …
=> adding try catch to getTokens()

package.json
Version update
sdk version 1.2.8
updated to version 1.2.9
No
* 
* **Note**:
a. You have done your changes in a separate branch. Branches MUST have descriptive …
=> updated version from 1.2.8 -> 1.2.9

package.json, src/aptos_client.test.ts, src/aptos_client.ts, src/wallet_client.ts
Update
simulateTransaction was taking complete aptos account which is useless
Changed and now it takes public key of the account only
Created local build -> installed it in wallet -> checked
No
* 
* **Note**:
1. Make sure that your PR is …
=> taking public key instead of complete account

src/wallet_client.ts
* Feature
* No functions to send and receive nfts
* Added functions to send and receive nfts
* No
* 
* **Note**:
a. You have done your changes in a separate …
=> Added functions for opt_in_direct_transfer and transfer_with_opt_in

package.json
=> version updated to v1.2.11

src/aptos_client.ts
=> handling max gas amount as adviced by Aptos

package.json, src/wallet_client.ts
Bug fix
Wrong estimate cost
fixed estimate cost
No
* 
* **Note**:
a. You have done your changes in a separate branch. Branches MUST have descriptive names that …
=> version bump + bug fix

src/faucet_client.ts, src/wallet_client.ts
Update
Padded address was returned after creating/importing new account
Now normal 66 length address will return
No
* 
* **Note**:
a. You have done your changes …
=> removed padding

package.json, src/wallet_client.test.ts, src/wallet_client.ts
Update
Wallet client test was not updated for padded address, updated version
Fixed above issues
No
* 
* **Note**:
a. You have done your changes in a separate …
=> updated version, fixed wallet client

package.json
=> 1.2.16 to 1.2.17

src/wallet_client.ts
=> Returning success and vm_status from transaction simulate

package.json
=> 1.2.17 to 1.2.18

package.json
=> Update sdk version

package.json
version bump
* 
* **Note**:
a. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or …
=> version bump from 1.2.19 -> 1.2.20

package.json
=> updated version from 1.2.20 -> 1.2.21

package.json
=> updated version from v1.2.21 -> 1.2.22

package.json
=> fixed lib versions

package.json
=> version bump: from 1.2.23 -> 1.2.24

src/wallet_client.ts
Bug fix
When out of 20 some account is not present in blockchain then importWallet function only imports first x accounts present in bc
Checking all 20 accounts if they are present in bc or not and importing till last account found in bc our of those 20
1. Create new wallet
2. Create 4 new accounts
3. Fund account 4 with some coins
4. Try to import. importWallet should import 4 accounts
* **Does this PR introduce a breaking change?** (What …
=> bug fix: fixed partial account import

src/utils/misc.ts
Fix
Default. expiration timestamp seconds is 20
Changed expiration timestamp seconds from 20 to 60
No
* 
* **Note**:
a. You have done your changes in a separate …
=> fix: increasing txn exp time from 20 sec to 60 sec

package.json
=> chore: updated version from 1.2.25 to 1.2.26

src/utils/misc.ts
=> chore: increased DEFAULT_TXN_EXP_SEC_FROM_NOW from 20 to 60

package.json, src/bcs/helper.ts, src/indexer/generated/operations.ts, src/indexer/generated/queries.ts, src/indexer/generated/types.ts, src/indexer/queries/getTokenData.graphql, src/plugins/aptos_token.ts, src/providers/indexer.ts, src/tests/e2e/aptos_client.test.ts, src/tests/e2e/aptos_token.test.ts, src/tests/e2e/faucet_client.test.ts, src/tests/e2e/fungible_asset_client.test.ts, src/tests/e2e/indexer.test.ts, src/version.ts
update
old changes as compare to latest aptos sdk
synced with latest aptos sdk
npm run test
no
* 
* **Note**:
a. You have done your changes in a separate branch. …
=> chore: synced with latest aptos sdk
